### ISSUE TITLE
bug: citation audit edit logs silently dropped — VALID_TOOLS missing crux-audit-source-replace and crux-audit-pass2

### ISSUE THREAD

**Issue by OAGr** [quantified-uncertainty/longterm-wiki#529]
## Problem

The citation audit pipeline (`crux/citations/audit.ts`) writes edit logs with tool values `"crux-audit-source-replace"` (line 285) and `"crux-audit-pass2"` (line 350). These are absent from `VALID_TOOLS` in `apps/wiki-server/src/api-types.ts:29`, introduced in PR #487.

The server validates `tool` via `z.enum(VALID_TOOLS)` and returns HTTP 400 on failure. Since the Postgres migration (PR #485), every citation audit run **silently drops its edit log entries**.

Confirmed by `npx tsc --noEmit` in crux/:
```
crux/citations/audit.ts(285,13): error TS2322: Type '"crux-audit-source-replace"' is not assignable to type 'EditTool'
crux/citations/audit.ts(350,13): error TS2322: Type '"crux-audit-pass2"' is not assignable to type 'EditTool'
```

## Fix

Add both to `VALID_TOOLS` in `api-types.ts` and to the `EditTool` union in `crux/lib/edit-log.ts`.

## Affected files
- `apps/wiki-server/src/api-types.ts:29`
- `crux/lib/edit-log.ts:27`
- `crux/citations/audit.ts:285,350`

**Comment by OAGr** [comment]
🤖 Claude Code has finished work on this issue.

**PR ready for review:** https://github.com/quantified-uncertainty/longterm-wiki/pull/542
